version: '3.0'
services:
  haste-server:
    build: .
    networks:
      - db-network
    environment:
      - STORAGE_TYPE=redis
      - STORAGE_HOST=redis
      - STORAGE_PORT=6379
    ports:
      - 7777:7777
    restart: always
  redis:
    image: redis:latest
    networks:
      - db-network
    restart: always

networks:
  db-network:
